"""引擎层 — 规则计算、战斗、施法、状态等核心系统。"""

from .attack_sequence import AttackPlan, AttackResult, AttackSequence
from .battle_map import BattleMap, GridCell
from .command import Command
from .coverage import CoverageEntry, CoverageManifest, CoverageStatus
from .damage import DamageComponent, DamagePacket
from .effect_dsl import EffectDefinition, EffectExecutor, EffectOpType, EffectOperation
from .effects import (
    DurationSpec,
    DurationType,
    EffectInstance,
    EffectManager,
    SourceRef,
    StackPolicyType,
)
from .entity_state import EntityState, EntityStateRegistry, EntityType
from .equipment_slots import EquipmentSlotsManager, ItemInstance, SlotType
from .health_state import DeathSaveState, HealthStateMachine, KnockoutState
from .mastery import MasteryEffect, MasteryGrant, resolve_mastery_with_grant
from .entity_lifecycle import (
    EntityLifecycleManager,
    FormOverride,
    SummonedEntity,
)
from .reaction_window import (
    ReactionController,
    ReactionOption,
    ReactionType,
    ReactionWindow,
    ReadyEffect,
    COUNTERSPELL_REACTION,
    DISPEL_MAGIC,
    LEGENDARY_RESISTANCE_WINDOW,
    SHIELD_REACTION,
    TIMING_SPELL_REGISTRY,
    get_timing_spell_window,
    open_timing_window,
)
from .rng import ReplayEngine, RngContext, RollRecord
from .ruleset_manifest import RulesetManifest, SourceBook, load_default_manifest
from .timing import TimingController, TimingHandler, TimingPoint, TimingQueue
from .scheduler import (
    DurationScheduler,
    RepeatSave,
    ScheduledEffect,
    SchedulerDurationType,
)
from .spell_slots import (
    FULL_CASTERS,
    HALF_CASTERS,
    PATRON_SLOTS,
    PACT_CASTERS,
    SpellSlotCalculator,
    THIRD_CASTERS,
    get_combined_slots,
    get_max_slots,
)
from .spell_targeting import (
    AreaShape,
    AreaSpec,
    RangeSpec,
    SpellTargetingService,
    TargetSpec,
    TargetType,
    get_spell_target_spec,
)
from .visibility import CoverLevel, VisibilityLevel, VisibilityResult, VisibilityService
from .weapon_rules import WeaponRuleContext, WeaponRuleHandler, WeaponRuleResult

from .spellcasting import (
    CasterState,
    MultiTargetSpellResult,
    SaveOutcome,
    SpellTarget,
    can_cast_by_components,
    can_cast_with_equipment_slots,
    check_casting_components,
    check_material_availability,
    compute_spell_attack_bonus,
    compute_spell_save_dc,
    cast_spell,
    consume_spell_slot,
    create_material_consumed_event,
    has_spell_slot,
    resolve_multi_ray_spell,
    resolve_save_outcome,
    resolve_upcast,
    restore_slots_on_long_rest,
    reset_turn_spell_count,
)

__all__ = [
    "AreaShape",
    "AreaSpec",
    "AttackPlan",
    "AttackResult",
    "AttackSequence",
    "BattleMap",
    "CasterState",
    "Command",
    "COUNTERSPELL_REACTION",
    "CoverLevel",
    "CoverageEntry",
    "CoverageManifest",
    "CoverageStatus",
    "DISPEL_MAGIC",
    "DamageComponent",
    "DamagePacket",
    "DeathSaveState",
    "DurationScheduler",
    "DurationSpec",
    "DurationType",
    "EffectDefinition",
    "EffectExecutor",
    "EffectInstance",
    "EffectManager",
    "EffectOpType",
    "EffectOperation",
    "EntityLifecycleManager",
    "EntityState",
    "EntityStateRegistry",
    "EntityType",
    "EquipmentSlotsManager",
    "FormOverride",
    "FULL_CASTERS",
    "GridCell",
    "HALF_CASTERS",
    "HealthStateMachine",
    "ItemInstance",
    "KnockoutState",
    "LEGENDARY_RESISTANCE_WINDOW",
    "MasteryEffect",
    "MasteryGrant",
    "PACT_CASTERS",
    "RangeSpec",
    "ReactionController",
    "ReactionOption",
    "ReactionType",
    "ReactionWindow",
    "ReadyEffect",
    "ReplayEngine",
    "RngContext",
    "RepeatSave",
    "RollRecord",
    "RulesetManifest",
    "SHIELD_REACTION",
    "SaveOutcome",
    "ScheduledEffect",
    "SchedulerDurationType",
    "SlotType",
    "SourceBook",
    "SourceRef",
    "SpellSlotCalculator",
    "SpellTarget",
    "SpellTargetingService",
    "StackPolicyType",
    "SummonedEntity",
    "THIRD_CASTERS",
    "TargetSpec",
    "TargetType",
    "TIMING_SPELL_REGISTRY",
    "TimingController",
    "TimingHandler",
    "TimingPoint",
    "TimingQueue",
    "VisibilityLevel",
    "VisibilityResult",
    "VisibilityService",
    "WeaponRuleContext",
    "WeaponRuleHandler",
    "WeaponRuleResult",
    "can_cast_by_components",
    "can_cast_with_equipment_slots",
    "cast_spell",
    "check_casting_components",
    "check_material_availability",
    "compute_spell_attack_bonus",
    "compute_spell_save_dc",
    "consume_spell_slot",
    "create_material_consumed_event",
    "get_combined_slots",
    "get_max_slots",
    "get_spell_target_spec",
    "get_timing_spell_window",
    "has_spell_slot",
    "load_default_manifest",
    "open_timing_window",
    "resolve_mastery_with_grant",
    "resolve_multi_ray_spell",
    "resolve_save_outcome",
    "resolve_upcast",
    "reset_turn_spell_count",
    "restore_slots_on_long_rest",
]
